[build-system]
requires = ["setuptools>=64", "wheel", 'tomli; python_version < "3.11"']
build-backend = "setuptools.build_meta"

[project]
name = "git"
version = "2.47.1"
description = "Git distributed version control system (pre-built)"
requires-python = ">=3.8"

[project.scripts]
"git" = "git:_run"

[tool.setuptools.packages.find]
include = ["git*"]

[tool.setuptools.package-data]
git = ["install/**/*", "*.so"]

[tool.shim]
repo_url = "https://github.com/greatgitsby/op-dependencies"
tag = "git/v2.47.1"
datadir = "install"
