[build-system]
requires = ["setuptools>=64", "wheel", 'tomli; python_version < "3.11"']
build-backend = "setuptools.build_meta"

[project]
name = "libyuv"
version = "1922.0"
description = "libyuv image processing library (static build) (pre-built)"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["libyuv*"]

[tool.setuptools.package-data]
libyuv = ["install/**/*", "*.so"]

[tool.shim]
repo_url = "https://github.com/greatgitsby/op-dependencies"
tag = "libyuv/v1922.0"
datadir = "install"
