[build-system]
requires = ["setuptools>=64", "wheel", 'tomli; python_version < "3.11"']
build-backend = "setuptools.build_meta"

[project]
name = "raylib"
version = "5.5.0.8"
description = "raylib + pyray Python bindings (commaai fork) (pre-built)"
requires-python = ">=3.8"
dependencies = ["cffi>=1.17.1"]

[tool.setuptools.packages.find]
include = ["raylib*", "pyray*"]

[tool.setuptools.package-data]
raylib = ["install/**/*", "*.so"]

[tool.shim]
repo_url = "https://github.com/greatgitsby/op-dependencies"
tag = "raylib/v5.5.0.8"
datadir = "install"
