[build-system]
requires = ["setuptools>=64", "wheel", 'tomli; python_version < "3.11"']
build-backend = "setuptools.build_meta"

[project]
name = "imgui"
version = "1.92.7"
description = "Dear ImGui + ImPlot + GLFW 3.4 (static) (pre-built)"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["imgui*"]

[tool.setuptools.package-data]
imgui = ["install/**/*", "*.so"]

[tool.shim]
repo_url = "https://github.com/greatgitsby/op-dependencies"
tag = "imgui/v1.92.7"
datadir = "install"
