[build-system]
requires = ["setuptools>=64", "wheel", 'tomli; python_version < "3.11"']
build-backend = "setuptools.build_meta"

[project]
name = "cppcheck"
version = "2.16.0"
description = "Cppcheck static analysis tool (pre-built)"
requires-python = ">=3.8"

[project.scripts]
"cppcheck" = "cppcheck:_run"

[tool.setuptools.packages.find]
include = ["cppcheck*"]

[tool.setuptools.package-data]
cppcheck = ["install/**/*", "*.so"]

[tool.shim]
repo_url = "https://github.com/greatgitsby/op-dependencies"
tag = "cppcheck/v2.16.0"
datadir = "install"
